### ISSUE TITLE
Using k8s_config with --arch linux_amd64 on macOS does not replace docker image fqn in template.

### ISSUE THREAD

**Issue by jamesjarvis** [thought-machine/pleasings#57]
While trying to build a k8s config (on macOS) using `plz build //src/app/k8s:k8s --arch linux_amd64` , the `image` tag will not be replaced in the k8s config.
This leads to an output k8s yaml file that contains something like:
```yaml
containers:
        - name: main
          image: //src/app/k8s:image
```
rather than:
```yaml
containers:
        - name: main
          image: dockerhub/app:2d3844e501499c95072cc2a9e27183d0ac0d2217bd9c73debd12c4efe626026c
```

The dockerfile is simple and looks like so:
```Dockerfile
FROM alpine:latest
COPY /app /app
ENTRYPOINT [ "/app" ] 
```
And the binary produced with --arch linux_amd64 + the docker image produced are both correct. It's just the image name replacement in the k8s template that's not working correctly.

Note that the image name replacement works fine without using the `--arch` flag
